<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ShiftsLogger.WebApi\LoggerService\LoggerService.csproj" />
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\Entity\Entity.csproj" />
      <ProjectReference Include="..\Service.Contracts\Service.Contracts.csproj" />
      <ProjectReference Include="..\Service\Service.csproj" />
      <ProjectReference Include="..\View\View.Contracts\View.Contracts.csproj" />
      <ProjectReference Include="..\View\View.Menu\View.Menu.csproj" />
      <ProjectReference Include="..\View\View.TableBuilderService\View.TableBuilderService.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <None Update="endpoints.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
