<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\View.Services.Contracts\View.Services.Contracts.csproj" />
      <ProjectReference Include="..\View.Utility\View.Utility.csproj" />
    </ItemGroup>

</Project>
