<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ShiftsLogger.WebApi\Shared\Shared.csproj" />
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\View\View.Contracts\View.Contracts.csproj" />
    </ItemGroup>

</Project>
