// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ShiftsLogger.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241211014755_AdjustedShiftModelToIncludeHoursWorkedColumnInDb")]
    partial class AdjustedShiftModelToIncludeHoursWorkedColumnInDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationId");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            Address = "777 Lucky Str. SW, Edmonton, AB, Canada",
                            Name = "Office"
                        },
                        new
                        {
                            Id = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            Address = "666 Sleepy Str. SW, Edmonton, AB, Canada",
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("Entities.Models.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursWorked")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("DATEDIFF(MINUTE, StartTime, EndTime) / 60.00", true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("974244f9-657c-4ed4-b9b9-acf4141365c9"),
                            Description = "Worked a shift on 2024-05-24",
                            EndTime = new DateTime(2024, 5, 24, 7, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("9d1636e6-fae1-4415-a1e4-3ee0ca0ce1a3"),
                            Description = "Worked a shift on 2024-05-25",
                            EndTime = new DateTime(2024, 5, 25, 1, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("0201e763-504b-4762-95a7-2336b1e12070"),
                            Description = "Worked a shift on 2024-06-03",
                            EndTime = new DateTime(2024, 6, 3, 14, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("bd54b1d1-f3bc-4169-a47f-4ddb0846db74"),
                            Description = "Worked a shift on 2024-06-04",
                            EndTime = new DateTime(2024, 6, 4, 14, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("3c2256b5-ef40-4794-a9a2-9787fd1328c3"),
                            Description = "Worked a shift on 2024-06-13",
                            EndTime = new DateTime(2024, 6, 13, 6, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("fda66f00-45ad-4e24-b8b6-75b19f26413c"),
                            Description = "Worked a shift on 2024-06-14",
                            EndTime = new DateTime(2024, 6, 14, 8, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("a8639cf9-b64c-4f52-a223-89830a6453ef"),
                            Description = "Worked a shift on 2024-06-23",
                            EndTime = new DateTime(2024, 6, 23, 2, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("6e45dacf-bbc8-4194-8de1-c36f058c35e4"),
                            Description = "Worked a shift on 2024-06-24",
                            EndTime = new DateTime(2024, 6, 24, 9, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("193f8e8c-7a10-418e-85e5-90655409f6ac"),
                            Description = "Worked a shift on 2024-07-03",
                            EndTime = new DateTime(2024, 7, 3, 14, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("83f55b2f-11d2-438c-a520-e0759ad633c6"),
                            Description = "Worked a shift on 2024-07-04",
                            EndTime = new DateTime(2024, 7, 4, 8, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("f84f3dcf-b652-44e9-adc4-7b494de151ae"),
                            Description = "Worked a shift on 2024-07-13",
                            EndTime = new DateTime(2024, 7, 13, 13, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 7, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("907769ad-4421-446a-a0cc-3c47a935ee44"),
                            Description = "Worked a shift on 2024-07-14",
                            EndTime = new DateTime(2024, 7, 14, 8, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 7, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("ed23c7ce-cda6-4539-ba0b-05e283fcca8a"),
                            Description = "Worked a shift on 2024-07-23",
                            EndTime = new DateTime(2024, 7, 23, 10, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("128ce800-27d9-43ca-a88d-2b2eab8dfa0a"),
                            Description = "Worked a shift on 2024-07-24",
                            EndTime = new DateTime(2024, 7, 24, 6, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("5c124381-8d88-440d-b632-11fb473858a5"),
                            Description = "Worked a shift on 2024-08-02",
                            EndTime = new DateTime(2024, 8, 2, 12, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("0a205db4-da35-40d2-9056-901af675d8b5"),
                            Description = "Worked a shift on 2024-08-03",
                            EndTime = new DateTime(2024, 8, 3, 15, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 0m,
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        });
                });

            modelBuilder.Entity("Entities.Models.ShiftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("ShiftTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            Name = "Morning Shift"
                        },
                        new
                        {
                            Id = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            Name = "Evening Shift"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Role")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d"),
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Role = "Designer"
                        },
                        new
                        {
                            Id = new Guid("cbe1f697-611c-431d-8503-e62d78615184"),
                            Email = "janesmith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Role = "Software Developer"
                        });
                });

            modelBuilder.Entity("Entities.Models.Shift", b =>
                {
                    b.HasOne("Entities.Models.Location", "Location")
                        .WithMany("Shifts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ShiftType", "ShiftType")
                        .WithMany("Shifts")
                        .HasForeignKey("ShiftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ShiftType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Entities.Models.ShiftType", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
