// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ShiftsLogger.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Entity.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationId");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            Address = "777 Lucky Str. SW, Edmonton, AB, Canada",
                            Name = "Office"
                        },
                        new
                        {
                            Id = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            Address = "666 Sleepy Str. SW, Edmonton, AB, Canada",
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("Entities.Models.Entity.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c1733c1-589c-4fd2-978e-46a8695c37ea"),
                            Description = "Worked a shift on 2024-05-22",
                            EndTime = new DateTime(2024, 5, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("e7d814d7-caa4-45db-aeca-4ddd37bbb38b"),
                            Description = "Worked a shift on 2024-05-23",
                            EndTime = new DateTime(2024, 5, 23, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("e2e73feb-4dbf-4e70-9977-82353927f84e"),
                            Description = "Worked a shift on 2024-06-01",
                            EndTime = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("64bc7c73-07df-418c-a92b-60751c1b37c4"),
                            Description = "Worked a shift on 2024-06-02",
                            EndTime = new DateTime(2024, 6, 2, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("80655015-d164-4133-b8a0-af5e8851f210"),
                            Description = "Worked a shift on 2024-06-11",
                            EndTime = new DateTime(2024, 6, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("f760b149-30b7-4ecc-9320-910cd129286f"),
                            Description = "Worked a shift on 2024-06-12",
                            EndTime = new DateTime(2024, 6, 12, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("f1ef0cdf-4e06-4871-8cd9-8319e44895f4"),
                            Description = "Worked a shift on 2024-06-21",
                            EndTime = new DateTime(2024, 6, 21, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("9bab4782-a30a-4438-8ccb-b4a4760aeefe"),
                            Description = "Worked a shift on 2024-06-22",
                            EndTime = new DateTime(2024, 6, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d")
                        },
                        new
                        {
                            Id = new Guid("82796461-6ede-4f6d-a988-9a0f7f35ca3d"),
                            Description = "Worked a shift on 2024-07-01",
                            EndTime = new DateTime(2024, 7, 1, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("b789f457-e47d-482d-b5ea-4a22e0ed9727"),
                            Description = "Worked a shift on 2024-07-02",
                            EndTime = new DateTime(2024, 7, 2, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("90286d40-395f-43a2-8212-109905a746ac"),
                            Description = "Worked a shift on 2024-07-11",
                            EndTime = new DateTime(2024, 7, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 7, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("aec53468-e3fb-41ff-a6b8-78d24ecbad84"),
                            Description = "Worked a shift on 2024-07-12",
                            EndTime = new DateTime(2024, 7, 12, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("d7367ce4-91aa-483c-ba09-89ca48d97259"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("da160e9a-de5f-4c8d-96d9-b2eee5f32d97"),
                            Description = "Worked a shift on 2024-07-21",
                            EndTime = new DateTime(2024, 7, 21, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("c99791da-0e1a-441f-9f75-1919c1d23cb8"),
                            Description = "Worked a shift on 2024-07-22",
                            EndTime = new DateTime(2024, 7, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            StartTime = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("8e321961-7dff-4ac6-94a1-da0e82562dca"),
                            Description = "Worked a shift on 2024-07-31",
                            EndTime = new DateTime(2024, 7, 31, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        },
                        new
                        {
                            Id = new Guid("973e71ef-e48d-44fc-b990-5ac61ae69cbe"),
                            Description = "Worked a shift on 2024-08-01",
                            EndTime = new DateTime(2024, 8, 1, 8, 0, 0, 0, DateTimeKind.Local),
                            LocationId = new Guid("4524ce96-d845-4f38-8699-4d5472285bc2"),
                            ShiftTypeId = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            StartTime = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            UserId = new Guid("cbe1f697-611c-431d-8503-e62d78615184")
                        });
                });

            modelBuilder.Entity("Entities.Models.Entity.ShiftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("ShiftTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b4f9afe-b143-48be-8c1f-b72b2fddbdab"),
                            Name = "Morning Shift"
                        },
                        new
                        {
                            Id = new Guid("9d670142-f75f-40db-9f96-2e7913b8ed05"),
                            Name = "Evening Shift"
                        });
                });

            modelBuilder.Entity("Entities.Models.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Role")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("487081eb-ce7a-45a9-8112-b0a563310e9d"),
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Role = "Designer"
                        },
                        new
                        {
                            Id = new Guid("cbe1f697-611c-431d-8503-e62d78615184"),
                            Email = "janesmith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Role = "Software Developer"
                        });
                });

            modelBuilder.Entity("Entities.Models.Entity.Shift", b =>
                {
                    b.HasOne("Entities.Models.Entity.Location", "Location")
                        .WithMany("Shifts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Entity.ShiftType", "ShiftType")
                        .WithMany("Shifts")
                        .HasForeignKey("ShiftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Entity.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ShiftType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Entity.Location", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Entities.Models.Entity.ShiftType", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Entities.Models.Entity.User", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
