<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\View.Menu\View.Menu.csproj" />
      <ProjectReference Include="..\View.Services.Contracts\View.Services.Contracts.csproj" />
      <ProjectReference Include="..\View.Services\View.Services.csproj" />
    </ItemGroup>

</Project>
